ALTER TABLE messages ADD COLUMN task_id TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN creator_agent_id TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN schema TEXT NOT NULL DEFAULT '';
