CREATE TABLE IF NOT EXISTS code_sessions (
    id                        TEXT PRIMARY KEY,
    agent_id                  TEXT NOT NULL,
    model_provider            TEXT NOT NULL DEFAULT '',
    model_name                TEXT NOT NULL DEFAULT '',
    idx                       INTEGER NOT NULL DEFAULT 0,
    is_active                 INTEGER NOT NULL DEFAULT 0,
    prompts                   INTEGER NOT NULL DEFAULT 0,
    last_sync_prompt          INTEGER NOT NULL DEFAULT 0,
    status                    TEXT NOT NULL DEFAULT 'ready',
    stop_reason               TEXT NOT NULL DEFAULT '',
    tokens_input              INTEGER NOT NULL DEFAULT 0,
    tokens_output             INTEGER NOT NULL DEFAULT 0,
    tokens_cached_input       INTEGER NOT NULL DEFAULT 0,
    tokens_cached_output      INTEGER NOT NULL DEFAULT 0,
    tokens_max                INTEGER NOT NULL DEFAULT 0,
    tokens_consumed_percent   REAL NOT NULL DEFAULT 0,
    is_interrupted            INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (agent_id) REFERENCES agents(id)
);
